logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_raif
    username: postgres
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
